/*
 * This source file was generated by the Gradle 'init' task
 */
package discord_clone_project_final;

public class App {
    public String getGreeting() {
        return "We are going to make a discord clone! This is the final project for our Java class.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
